package CatsTransfer;
import Technical.Tech;
import java.util.ArrayList;
import java.util.List;

public class CatBuilder implements Database{

    //Generates new Address object and fills it with random values from static arrays.
    private static Address randomAddress(){

        return new Address(
                cities[Tech.getRandom(0, cities.length-1)],
                streetTypes[Tech.getRandom(0, streetTypes.length-1)],
                streetNames[Tech.getRandom(0, streetNames.length-1)],
                String.valueOf(Tech.getRandom(1, 200)));
    }

    /*
    * Creates new List collection and fills it out with Cat objets created with random 'name' abd 'address' fields.
    * Name taken from Database implemented variable 'names' and address is generated by randomAddress() method.
    */
    public static List<Cat> fillCatsList(int amount){
        List<Cat> catsList = new ArrayList<>();
        for(int i = 0; i < amount; i++){
            catsList.add(new Cat(names[Tech.getRandom(0, names.length-1)], randomAddress()));
        }
        return catsList;
    }

    /*
    * Calls changeAddress() of each object in received as a parameter 'catsList' List collection.
    * Returns List collection with changed Cat objects where 'address' has been changed to a new value generated by
    * randomAddress() method.
    */
    public static List<Cat> changeCatsAddress(List<Cat> catsList) {
        catsList.forEach( c -> c.changeAddress(randomAddress()));
        return catsList;
    }
}
